module.exports = {
    SUCCESS: 200,

    NOT_FOUND: 404,

    NO_LOGIN: 401,

    INTERNAL_ERROR: 500,

    // Custom status code
    RESOURCE_DUPLICATED: 512,
    COMMUNICATION_WITH_THIRDPARTY_FAILED: 513,
    FORM_VALIDATION_ERROR: 514
};
